<a href="https://colab.research.google.com/github/hoangnuthuphuong/python/blob/Phuong/Pandas01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Câu 1: Khởi tạo 1 Series với giá trị rỗng

In [4]:
import pandas
pandas.Series()
import numpy


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  


Câu 2: Giả sử có 1 vector hàng a có kích thước (1x7) được biểu diễn trong NumPy, hãy tạo 1
series tương ứng với các giá trị được sinh ngẫu nhiên.

In [5]:
a = numpy.random.randint(0,50,[1,7])
pandas.Series([a])

0    [[49, 27, 6, 49, 8, 15, 42]]
dtype: object

Câu 3: Giả sử có 1 vector hàng a có kích thước (1x7), hãy nhập các giá trị cho 7 phần tử này từ
bàn phím và tạo series tương ứng.

In [6]:
A = numpy.arange(1, 8, 1)
b = []
for i in range(1, 8):
  print("Nhập phần tử thứ", i, "=", end = " ")
  b.append(int(input()))
print(A)
s = pandas.Series(b , A, int)
print(s)

Nhập phần tử thứ 1 = 2
Nhập phần tử thứ 2 = 4
Nhập phần tử thứ 3 = 5
Nhập phần tử thứ 4 = 6
Nhập phần tử thứ 5 = 2
Nhập phần tử thứ 6 = 1
Nhập phần tử thứ 7 = 1
[1 2 3 4 5 6 7]
1    2
2    4
3    5
4    6
5    2
6    1
7    1
dtype: int64


Câu 4: Giả sử có 1 vector cột có kích thước (7x1) được biểu diễn trong NumPy, hãy tạo Series
tương ứng.

In [7]:
a = numpy.random.randint(1,10,[7,1])
print("vector cột: ")
print(a)
b = a.reshape(7,)
print("series tương ứng")
print(pandas.Series(b))

vector cột: 
[[6]
 [7]
 [3]
 [1]
 [8]
 [9]
 [2]]
series tương ứng
0    6
1    7
2    3
3    1
4    8
5    9
6    2
dtype: int64


Câu 5: Chuyển đổi dữ liệu, hãy thực hiện các yêu cầu sau:
- Chuyển 1 list thành 1 series
- Chuyển 1 tuple thành 1 series
- Chuyển 1 dictionary thành 1 series

In [8]:
n = int(input("Số phần tử của list: "))
list1 = list(range(n))
print(list1)
print("Chuyển list thành series: ",pandas.Series([list1]))


Số phần tử của list: 4
[0, 1, 2, 3]
Chuyển list thành series:  0    [0, 1, 2, 3]
dtype: object


In [ ]:
n = int(input("Số phần tử của tuple: "))
tuple1 = tuple(range(n))
print(tuple)
print("Chuyển tuple thành series: ",pandas.Series([tuple1]))

Số phần tử của tuple: 5
<class 'tuple'>
Chuyển tuple thành series:  0    (0, 1, 2, 3, 4)
dtype: object


In [ ]:
dic1 = {'phuong': 'Cute', 'birthday': 17}
print(dic1)
print("Chuyển dictionary thành series:\n ", pandas.Series(dic1))

{'phuong': 'Cute', 'birthday': 17}
Chuyển dictionary thành series:
  phuong      Cute
birthday      17
dtype: object


Câu 6: Mỗi phần tử của series đều gắn liền với các chỉ số (index) tương ứng, hãy tạo một series
có kích thước (1x20) với giá trị ngẫu nhiên:
- Xuất series ra màn hình
- Xuất các chỉ số của series ra màn hình
- Thay đổi cách đánh chỉ số mặc định của series từ đánh chỉ số bằng số nguyên sang các kiểu
đánh chỉ số bằng label và in kết quả ra màn hình
Gợi ý:
- Hàm loc() dùng cho chỉ số label
- Hàm iloc() dùng cho chỉ số đạng số nguyên
- Hàm ix(): dùng cho cả 2 loại chỉ số trên

In [ ]:
x = numpy.random.randint(1,20,[1,20])
print(pandas.Series([x]))

0    [[9, 4, 2, 5, 18, 9, 16, 9, 10, 2, 17, 17, 9, ...
dtype: object


Câu 7: Giả sử có series có kích thước (1x10), giá trị ngẫu nhiên, index được đánh từ ‘a’ trở đi,
hãy:
- Trích xuất các phần tử của Series có chỉ số là ‘a’, ‘c’, ‘e’
- Trích xuất các phần tử của Series có chỉ số từ 3 đến 6

In [9]:
a = pandas.Series(numpy.random.randint(1,10,[10]))
l2 = ['a','b','c','d','e','f','g','h','l','m']
a.index = l2
print(b)
print("chỉ số a: ",a.loc['a'])
print("chỉ số c: ",a.loc['c'])
print("chỉ số e: ",a.loc['e'])

[6 7 3 1 8 9 2]
chỉ số a:  3
chỉ số c:  3
chỉ số e:  3


In [ ]:
b = pandas.Series(numpy.random.randint(1,10,[10]))
print(b)
print("Các phần tử của Series có chỉ số từ 3 đến 6:\n",b.iloc[2:7])

0    1
1    7
2    3
3    1
4    8
5    4
6    4
7    9
8    5
9    9
dtype: int64
Các phần tử của Series có chỉ số từ 3 đến 6:
 2    3
3    1
4    8
5    4
6    4
dtype: int64
